version: "3.8"

services:
  redis:
    image: redis
    container_name: redis

  frontend:
    image: frontend
    build: ./example-frontend
    ports:
      - 5000:5000
    container_name: frontend
    depends_on:
      - backend
      
  backend:
    image: backend
    build: ./example-backend
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis