version: "3.8"

services:
  
  redis:
    image: redis:alpine
    container_name: redis

  frontend:
    image: frontend
    build: ./example-frontend
    ports:
      - 5000:5000
    container_name: frontend
    depends_on:
      - backend
      
  backend:
    image: backend
    build: ./example-backend
    ports:
      - 8080:8080
    container_name: backend
    environment:
      - REDIS_HOST=redis
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
    depends_on:
      - redis

  db:
    image: postgres:13.2-alpine
    restart: unless-stopped
    environment:
      POSTGRES_PASSWORD: example
    container_name: db_redmine
    volumes:
      - database:/var/lib/postgresql/data

volumes:
  database: